
name: Add-On
on: repository_dispatch

jobs:
  Run-Add-On:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: ${{ github.event.client_payload.id }}
        run: echo run identifier ${{ github.event.client_payload.id }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run add-on
        run: python main.py '${{ toJSON(github.event.client_payload) }}'

---

name: Update config
on: push
  branches:
    - main
  paths:
    - config.yaml

jobs:
  Update-Config:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Notify DocumentCloud to update
        run: curl "https://api.www.documentcloud.org/api/add_ons/notify/?name=${{ github.repository }}"

