
name: Update config
on:
  push:
    branches:
      - main
    paths:
      - config.yaml

jobs:
  Update-Config:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Notify DocumentCloud to update
        run: curl "https://api.www.documentcloud.org/api/add_ons/notify/?name=${{ github.repository }}"
