
name: Plugins Proof of Concept
on: repository_dispatch

jobs:
  Run-Plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: echo "Running"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: python main.py ${{ toJSON(github.event.client_payload) }}
